network:
  version: 2
  ethernets:
    eth1:
      dhcp4: no
      dhcp6: no
      optional: true
      addresses: [<IP_address>/<subnet_mask>]
      gateway4: <gateway_IP>
      nameservers:
        addresses: [<DNS_server_IP>]
    eth2:
      dhcp4: no
      dhcp6: no
      optional: true
      addresses: [<IP_address>/<subnet_mask>]
      gateway4: <gateway_IP>
      nameservers:
        addresses: [<DNS_server_IP>]
    eth3:
      dhcp4: no
      dhcp6: no
      optional: true
      addresses: [<IP_address>/<subnet_mask>]
      gateway4: <gateway_IP>
      nameservers:
        addresses: [<DNS_server_IP>]
  vlans:
    vlan10:
      id: 10
      link: eth1
      addresses: [<VLAN10_IP_address>/<subnet_mask>]
      gateway4: <VLAN10_gateway_IP>
      nameservers:
        addresses: [<VLAN10_DNS_server_IP>]
    vlan20:
      id: 20
      link: eth2
      addresses: [<VLAN20_IP_address>/<subnet_mask>]
      gateway4: <VLAN20_gateway_IP>
      nameservers:
        addresses: [<VLAN20_DNS_server_IP>]
    vlan30:
      id: 30
      link: eth3
      addresses: [<VLAN30_IP_address>/<subnet_mask>]
      gateway4: <VLAN30_gateway_IP>
      nameservers:
        addresses: [<VLAN30_DNS_server_IP>]
   
