   network:
  version: 2
  ethernets:
    eth1:
      dhcp4: no
      dhcp6: no
      optional: true
      addresses: [<IP_address>/<subnet_mask>]
      gateway4: <gateway_IP>
      nameservers:
        addresses: [<DNS_server_IP>]
    eth2:
      dhcp4: no
      dhcp6: no
      optional: true
      addresses: [<IP_address>/<subnet_mask>]
      gateway4: <gateway_IP>
      nameservers:
        addresses: [<DNS_server_IP>]
    eth3:
      dhcp4: no
      dhcp6: no
      optional: true
      addresses: [<IP_address>/<subnet_mask>]
      gateway4: <gateway_IP>
      nameservers:
        addresses: [<DNS_server_IP>]
  vlans:
    vlan10:
      id: 10
      link: eth1
    vlan20:
      id: 20
      link: eth2
    vlan30:
      id: 30
      link: eth3
   
