version: "3"

services:
  vscode:
    build:
      context: vscode
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # volume used to access the `notebooks` folder
      - ../notebooks:/home/coder/project
    environment:
      - PASSWORD=yourpassword

  grafana:
    image: grafana/grafana:9.4.7
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - questdb

  questdb:
    image: questdb/questdb:7.1.1
    ports:
      - "8812:8812"
      - "9000:9000"
      - "9009:9009"
      - "9003:9003" 
    volumes:
      - questdb-data:/root/.questdb
    environment:
      - QDB_PG_USER=admin
      - QDB_PG_PASSWORD=quest


volumes:
  grafana-data:
  questdb-data:
