version: "3"

services:
  vscode:
    build:
      context: vscode
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # volume used to access the `notebooks` folder
      - ../notebooks:/home/coder/project
    environment:
      - PASSWORD=yourpassword

  grafana:
    image: grafana/grafana:9.4.7
    user: "${UID}:${GID}"
    ports:
      - "3000:3000"
    volumes:
      - .volumes/grafana/data:/var/lib/grafana
      # volume used to set up the datasource
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    # environment:
    #   - GF_SECURITY_ADMIN_PASSWORD=yourpassword

  questdb:
    image: questdb/questdb:7.1.1
    ports:
      - "9000:9000"
      - "8812:8812"
    environment:
      # - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=qdb
