---
# Switch Configuration
switch:
  - name: Layer3Switch
    ip_routing: true
    static_routes:
      - destination_network: 0.0.0.0
        subnet_mask: 0.0.0.0
        next_hop: 10.10.100.2       
    interfaces:
      - name: Ethernet0
        no_switchport: true
        ip_address: 192.168.100.1
        subnet_mask: 255.255.255.0   
      - name: Ethernet1
        mode: access
        vlan: 10
      - name: Ethernet2
        mode: access
        vlan: 20
      - name: Ethernet3
        mode: access
        vlan: 30
      - name: Ethernet4
        mode: access
        vlan: 10
      - name: Ethernet5
        mode: access
        vlan: 20
      - name: Ethernet6
        mode: access
        vlan: 30
      - name: Ethernet7
        mode: access
        vlan: 10
      - name: Ethernet8
        mode: access
        vlan: 20
      - name: Ethernet9
        mode: access
        vlan: 30
      - name: Ethernet10
        mode: access
        vlan: 10
      - name: Ethernet11
        mode: access
        vlan: 20
      - name: Ethernet12
        mode: access
        vlan: 30
      - name: Ethernet13
        mode: access
        vlan: 10
      - name: Ethernet14
        mode: access
        vlan: 20
      - name: Ethernet15
        mode: access
        vlan: 30
      - name: Ethernet16
        mode: access
        vlan: 10
      - name: Ethernet17
        mode: access
        vlan: 20
      - name: Ethernet18
        mode: access
        vlan: 30
      - name: Ethernet19
        mode: access
        vlan: 10
      - name: Ethernet20
        mode: access
        vlan: 20
      - name: Ethernet21
        mode: access
        vlan: 30
      - name: Ethernet22
        mode: access
        vlan: 10
      - name: Ethernet23
        mode: access
        vlan: 20
      - name: Ethernet24
        mode: access
        vlan: 30
      - name: Ethernet25
        mode: access
        vlan: 10
      - name: Ethernet26
        mode: access
        vlan: 20
      - name: Ethernet27
        mode: access
        vlan: 30
      - name: Ethernet28
        mode: access
        vlan: 10
      - name: Ethernet29
        mode: access
        vlan: 20
      - name: Ethernet30
        mode: access
        vlan: 30
      - name: Ethernet31
        mode: access
        vlan: 10
      - name: Ethernet32
        mode: access
        vlan: 20
      - name: Ethernet33
        mode: access
        vlan: 30
      - name: Ethernet34
        mode: access
        vlan: 10
      - name: Ethernet35
        mode: access
        vlan: 20
      - name: Ethernet36
        mode: access
        vlan: 30
# Router Configuration
router:
  - name: Router
    interfaces:
      - name: Ethernet0/0
      # Use Public IP address here (router end)
        ip_address: 203.0.113.1
        subnet_mask: 255.255.192.0
      - name: Ethernet0/1
      #Use Public IP address (ISP end)
        ip_address: 192.168.100.2
        subnet_mask: 255.255.255.0
    static_routes:
      - destination_network: 0.0.0.0
        subnet_mask: 0.0.0.0
        next_hop: 203.0.113.1
      - destination_network: 192.168.0.0
        subnet_mask: 255.255.0.0
        next_hop: 192.168.100.1
    static_nats:
      - source_ip: 192.168.10.10
        translated_ip: 203.0.113.3
      - source_ip: 192.168.20.10
        translated_ip: 203.0.113.4
      - source_ip: 192.168.30.10
        translated_ip: 203.0.113.5
      - source_ip: 192.168.10.20
        translated_ip: 203.0.113.6
      - source_ip: 192.168.20.20
        translated_ip: 203.0.113.7
      - source_ip: 192.168.30.20
        translated_ip: 203.0.113.8
      - source_ip: 192.168.10.30
        translated_ip: 203.0.113.9
      - source_ip: 192.168.20.30
        translated_ip: 203.0.113.10
      - source_ip: 192.168.30.30
        translated_ip: 203.0.113.11
      - source_ip: 192.168.10.31
        translated_ip: 203.0.113.12
      - source_ip: 192.168.20.31
        translated_ip: 203.0.113.13
      - source_ip: 192.168.30.31
        translated_ip: 203.0.113.14
      - source_ip: 192.168.10.32
        translated_ip: 203.0.113.15
      - source_ip: 192.168.20.32
        translated_ip: 203.0.113.16
      - source_ip: 192.168.30.32
        translated_ip: 203.0.113.17
      - source_ip: 192.168.10.33
        translated_ip: 203.0.113.18
      - source_ip: 192.168.20.33
        translated_ip: 203.0.113.19
      - source_ip: 192.168.30.33
        translated_ip: 203.0.113.20
      - source_ip: 192.168.10.34
        translated_ip: 203.0.113.21
      - source_ip: 192.168.20.34
        translated_ip: 203.0.113.22
      - source_ip: 192.168.30.34
        translated_ip: 203.0.113.23
      - source_ip: 192.168.10.35
        translated_ip: 203.0.113.24
      - source_ip: 192.168.20.35
        translated_ip: 203.0.113.25
      - source_ip: 192.168.30.35
        translated_ip: 203.0.113.26  
      - source_ip: 192.168.10.36
        translated_ip: 203.0.113.27
      - source_ip: 192.168.20.36
        translated_ip: 203.0.113.28
      - source_ip: 192.168.30.36
        translated_ip: 203.0.113.29
      - source_ip: 192.168.10.37
        translated_ip: 203.0.113.30
      - source_ip: 192.168.20.37
        translated_ip: 203.0.113.31
      - source_ip: 192.168.30.37
        translated_ip: 203.0.113.32
      - source_ip: 192.168.10.38
        translated_ip: 203.0.113.33 
      - source_ip: 192.168.20.38   
        translated_ip: 203.0.113.34
      - source_ip: 192.168.30.38
        translated_ip: 203.0.113.35
      - source_ip: 192.168.10.39
        translated_ip: 203.0.113.36
      - source_ip: 192.168.20.39
        translated_ip: 203.0.113.37
      - source_ip: 192.168.30.39
        translated_ip: 203.0.113.38
      
# Servers Configuration
servers:
  - name: MonitoringServer
    interfaces:
      - name: eth1
        ip_address: 192.168.10.10
        subnet_mask: 255.255.255.0
        vlan: 10
        default_gateway: 192.168.10.1

      - name: eth2
        ip_address: 192.168.20.10
        subnet_mask: 255.255.255.0
        vlan: 20
        default_gateway: 192.168.20.1

      - name: eth3
        ip_address: 192.168.30.10
        subnet_mask: 255.255.255.0
        vlan: 30
        default_gateway: 192.168.30.1
  - name: GPUServer
    interfaces:
      - name: eth1
        ip_address: 192.168.10.20
        subnet_mask: 255.255.255.0
        vlan: 10
        default_gateway: 192.168.10.1

      - name: eth2
        ip_address: 192.168.20.20
        subnet_mask: 255.255.255.0
        vlan: 20
        default_gateway: 192.168.20.1
      - name: eth3
        ip_address: 192.168.30.20
        subnet_mask: 255.255.255.0
        vlan: 30
        default_gateway: 192.168.30.1
  - name: Microserver1
    interfaces:
      - name: eth1
        ip_address: 192.168.10.30
        subnet_mask: 255.255.255.0
        vlan: 10
        default_gateway: 192.168.10.1
      - name: eth2
        ip_address: 192.168.20.30
        subnet_mask: 255.255.255.0
        vlan: 20
        default_gateway: 192.168.20.1
      - name: eth3
        ip_address: 192.168.30.30
        subnet_mask: 255.255.255.0
        vlan: 30
        default_gateway: 192.168.30.1
  - name: Microserver2
    interfaces:
      - name: eth1
        ip_address: 192.168.10.31
        subnet_mask: 255.255.255.0
        vlan: 10
        default_gateway: 192.168.10.1
      - name: eth2
        ip_address: 192.168.20.31
        subnet_mask: 255.255.255.0
        vlan: 20
        default_gateway: 192.168.20.1
      - name: eth3
        ip_address: 192.168.30.31
        subnet_mask: 255.255.255.0
        vlan: 30
        default_gateway: 192.168.30.1
  - name: Microserver3
    interfaces:
      - name: eth1
        ip_address: 192.168.10.33
        subnet_mask: 255.255.255.0
        vlan: 10
        default_gateway: 192.168.10.1
      - name: eth2
        ip_address: 192.168.20.33
        subnet_mask: 255.255.255.0
        vlan: 20
        default_gateway: 192.168.20.1
      - name: eth3
        ip_address: 192.168.30.33
        subnet_mask: 255.255.255.0
        vlan: 30
        default_gateway: 192.168.30.1
  - name: Microserver4
    interfaces:
      - name: eth1
        ip_address: 192.168.10.34
        subnet_mask: 255.255.255.0
        vlan: 10
        default_gateway: 192.168.10.1
      - name: eth2
        ip_address: 192.168.20.34
        subnet_mask: 255.255.255.0
        vlan: 20
        default_gateway: 192.168.20.1
      - name: eth3
        ip_address: 192.168.30.34
        subnet_mask: 255.255.255.0
        vlan: 30
        default_gateway: 192.168.30.1
  - name: Microserver5
    interfaces:
      - name: eth1
        ip_address: 192.168.10.35
        subnet_mask: 255.255.255.0
        vlan: 10
        default_gateway: 192.168.10.1
      - name: eth2
        ip_address: 192.168.20.35
        subnet_mask: 255.255.255.0
        vlan: 20
        default_gateway: 192.168.20.1
      - name: eth3
        ip_address: 192.168.30.35
        subnet_mask: 255.255.255.0
        vlan: 30
        default_gateway: 192.168.30.1
  - name: Microserver6
    interfaces:
      - name: eth1
        ip_address: 192.168.10.36
        subnet_mask: 255.255.255.0
        vlan: 10
        default_gateway: 192.168.10.1
      - name: eth2
        ip_address: 192.168.20.36
        subnet_mask: 255.255.255.0
        vlan: 20
        default_gateway: 192.168.20.1
      - name: eth3
        ip_address: 192.168.30.36
        subnet_mask: 255.255.255.0
        vlan: 30
        default_gateway: 192.168.30.1
  - name: Microserver7
    interfaces:
      - name: eth1
        ip_address: 192.168.10.37
        subnet_mask: 255.255.255.0
        vlan: 10
        default_gateway: 192.168.10.1
      - name: eth2
        ip_address: 192.168.20.37
        subnet_mask: 255.255.255.0
        vlan: 20
        default_gateway: 192.168.20.1
      - name: eth3
        ip_address: 192.168.30.37
        subnet_mask: 255.255.255.0
        vlan: 30
        default_gateway: 192.168.30.1
  - name: Microserver8
    interfaces:
      - name: eth1
        ip_address: 192.168.10.38
        subnet_mask: 255.255.255.0
        vlan: 10
        default_gateway: 192.168.10.1
      - name: eth2
        ip_address: 192.168.20.38
        subnet_mask: 255.255.255.0
        vlan: 20
        default_gateway: 192.168.20.1
      - name: eth3
        ip_address: 192.168.30.38
        subnet_mask: 255.255.255.0
        vlan: 30
        default_gateway: 192.168.30.1  
  - name: Microserver9
    interfaces:
      - name: eth1
        ip_address: 192.168.10.39
        subnet_mask: 255.255.255.0
        vlan: 10
        default_gateway: 192.168.10.1
      - name: eth2
        ip_address: 192.168.20.39
        subnet_mask: 255.255.255.0
        vlan: 20
        default_gateway: 192.168.20.1
      - name: eth3
        ip_address: 192.168.30.39
        subnet_mask: 255.255.255.0
        vlan: 30
        default_gateway: 192.168.30.1
  - name: Microserver10
    interfaces:
      - name: eth1
        ip_address: 192.168.10.40
        subnet_mask: 255.255.255.0
        vlan: 10
        default_gateway: 192.168.10.1
      - name: eth2
        ip_address: 192.168.20.40
        subnet_mask: 255.255.255.0
        vlan: 20
        default_gateway: 192.168.20.1
      - name: eth3
        ip_address: 192.168.30.40
        subnet_mask: 255.255.255.0
        vlan: 30
        default_gateway: 192.168.30.1         